/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import model.Carro;
import sql.conexionsql;
import sql.Conexao;
import java.sql.Connection;


import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import dao.CarroDAO;
import dao.ClienteDAO;
import model.Cliente;

/**
 *
 * @author jose
 */
public class Exposicao extends javax.swing.JFrame {

    /**
     * Creates new form Exposicao
     */
    public Exposicao() {
        initComponents();
        jTabbedPane1.removeAll();
        jTabbedPane1.addTab("Exposição", jPanel2);
        jTextField2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jCorVermelha = new javax.swing.JRadioButton();
        jCorPreta = new javax.swing.JRadioButton();
        jCorBranca = new javax.swing.JRadioButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCambio = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        btnComprar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtnome = new javax.swing.JTextField();
        txtcpf = new javax.swing.JTextField();
        txtendereco = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnFinalizarCompra = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jValor = new javax.swing.JTextField();
        jDados = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txttelefone = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jTextField1.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jPanel2.add(jTextField1);
        jTextField1.setBounds(270, 60, 180, 50);

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel2.setText("Cambio:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(510, 130, 110, 30);

        jTextField2.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jTextField2.setText("R$1.500,00/Mês");
        jPanel2.add(jTextField2);
        jTextField2.setBounds(270, 250, 190, 50);

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel4.setText("Modelo:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 120, 110, 30);

        jTextField3.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jPanel2.add(jTextField3);
        jTextField3.setBounds(20, 150, 180, 50);

        buttonGroup1.add(jCorVermelha);
        jCorVermelha.setText("3");
        jPanel2.add(jCorVermelha);
        jCorVermelha.setBounds(190, 290, 93, 23);

        buttonGroup1.add(jCorPreta);
        jCorPreta.setText("1");
        jPanel2.add(jCorPreta);
        jCorPreta.setBounds(20, 290, 31, 23);

        buttonGroup1.add(jCorBranca);
        jCorBranca.setText("2");
        jPanel2.add(jCorBranca);
        jCorBranca.setBounds(100, 290, 93, 23);

        jTextField4.setBackground(new java.awt.Color(255, 0, 0));
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTextField4);
        jTextField4.setBounds(190, 260, 30, 30);

        jTextField5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jTextField5);
        jTextField5.setBounds(20, 260, 30, 30);

        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTextField6);
        jTextField6.setBounds(100, 260, 30, 30);

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel3.setText("Cor:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 220, 110, 30);

        jCambio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCambio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecionar:", "Automatico", "Manual" }));
        jPanel2.add(jCambio);
        jCambio.setBounds(510, 160, 100, 40);

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel6.setText("Marca:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 30, 80, 30);

        jTextField7.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField7);
        jTextField7.setBounds(20, 60, 180, 50);

        btnComprar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnComprar.setText("Alugar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        jPanel2.add(btnComprar);
        btnComprar.setBounds(510, 240, 140, 60);

        jLabel17.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel17.setText("Potencia:");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(270, 120, 110, 30);

        jTextField15.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jPanel2.add(jTextField15);
        jTextField15.setBounds(270, 150, 180, 50);

        jLabel21.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel21.setText("Ano:");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(270, 30, 110, 30);

        jTabbedPane1.addTab("Carro", jPanel2);

        jPanel5.setLayout(null);

        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        jPanel5.add(txtnome);
        txtnome.setBounds(90, 200, 170, 30);
        jPanel5.add(txtcpf);
        txtcpf.setBounds(370, 200, 170, 30);

        txtendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtenderecoActionPerformed(evt);
            }
        });
        jPanel5.add(txtendereco);
        txtendereco.setBounds(370, 300, 170, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Nome:");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(10, 200, 80, 29);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("CPF:");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(310, 200, 50, 29);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Endereço:");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(260, 300, 110, 29);

        btnFinalizarCompra.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnFinalizarCompra.setText("Alugar");
        btnFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCompraActionPerformed(evt);
            }
        });
        jPanel5.add(btnFinalizarCompra);
        btnFinalizarCompra.setBounds(230, 360, 120, 40);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(null);

        jValor.setEditable(false);
        jValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValorActionPerformed(evt);
            }
        });
        jPanel6.add(jValor);
        jValor.setBounds(330, 100, 140, 30);

        jDados.setEditable(false);
        jPanel6.add(jDados);
        jDados.setBounds(290, 10, 250, 40);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Valor:");
        jPanel6.add(jLabel19);
        jLabel19.setBounds(290, 100, 40, 17);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(0, 0, 790, 170);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("E-mail:");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(10, 250, 80, 29);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("Telefone:");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(260, 250, 100, 29);

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel5.add(txtemail);
        txtemail.setBounds(90, 250, 170, 30);

        txttelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefoneActionPerformed(evt);
            }
        });
        jPanel5.add(txttelefone);
        txttelefone.setBounds(370, 250, 170, 30);

        jTabbedPane1.addTab("Finalizar Compra", jPanel5);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 800, 580);

        jMenu1.setText("Administrador");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtenderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtenderecoActionPerformed

    private void btnFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCompraActionPerformed
        // Cadastro informações sobre o cliente
        String nome = txtnome.getText();
        String cpf = txtcpf.getText();
        String email = txtemail.getText();
        
        String telefone = txttelefone.getText();
        
        String endereco = txtendereco.getText();
        
        
        Cliente usuario = new Cliente (nome, cpf, email, telefone, endereco);

        try {
            Connection conexao = new Conexao().getConnection();
            ClienteDAO cadastro =  new ClienteDAO(conexao);
            cadastro.insert(usuario);
            JOptionPane.showMessageDialog(null, "Você acabou de alugar um carro da nossa empresa, Parabéns","Locadora",JOptionPane.INFORMATION_MESSAGE);
            jTabbedPane1.removeAll();
            jTabbedPane1.addTab("Exposição", jPanel2);
        } catch (SQLException ex) {
            Logger.getLogger(Exposicao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFinalizarCompraActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // Cadastro informações sobre o cliente
        String marca = jTextField7.getText();
        String modelo = jTextField3.getText();
        String ano = jTextField1.getText();
        
        String cor = "";
        if (jCorPreta.isSelected())
        cor+="Preto ";
        if (jCorBranca.isSelected())
        cor+="Branco ";
        if (jCorVermelha.isSelected())
        cor+="Vermelho ";
        
        String cambio = (String)jCambio.getSelectedItem();
        
        String potencia = jTextField15.getText();
         
        String preco = jTextField2.getText();
        
        Carro usuario = new Carro (marca, modelo, ano, cor, cambio, potencia, preco);

        try {
            Connection conexao = new Conexao().getConnection();
            CarroDAO cadastro =  new CarroDAO(conexao);
            cadastro.insert(usuario);

        } catch (SQLException ex) {
            Logger.getLogger(Exposicao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jDados.setText(jTextField7.getText()+" "+jTextField3.getText()+jTextField1.getText());
        jValor.setText(jTextField2.getText());
                
        jTabbedPane1.removeAll();
        jTabbedPane1.addTab("Finalizar Compra",jPanel5);
        
    }//GEN-LAST:event_btnComprarActionPerformed
    
    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void jValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValorActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_jValorActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txttelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefoneActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exposicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exposicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exposicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exposicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exposicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnFinalizarCompra;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox jCambio;
    private javax.swing.JRadioButton jCorBranca;
    private javax.swing.JRadioButton jCorPreta;
    private javax.swing.JRadioButton jCorVermelha;
    private javax.swing.JTextField jDados;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jValor;
    private javax.swing.JTextField txtcpf;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}
